name: Python test

on:
  push:
    branches:
      - main
  pull_request:
    types: [reopened, ready_for_review, synchronize, opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Run tests
        run: coverage run -m unittest discover

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
